version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: order_service_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "sh", "-c",
      "sleep 5 && migrate -source=file:///migrations -database=postgres://myuser:mypassword@db:5432/order_service_db?sslmode=disable up"
    ]

volumes:
  pgdata:
